version: "3.7"

services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile

    restart: always

    tty: true

    env_file: .env

    volumes:
      - ./logs:/app/logs
      - ./bot:/app/bot
