    quotes = [
        "Get busy living or get busy dying.",
        "You only live once, but if you do it right, once is enough.",
        "Many of life’s failures are people who did not realize how close they were to success when they gave up.",
        "If you want to live a happy life, tie it to a goal, not to people or things.",
        "Not how long, but how well you have lived is the main thing.",
        "If life were predictable it would cease to be life, and be without flavor.",
        "The greatest glory in living lies not in never falling, but in rising every time we fall.",
        "The way to get started is to quit talking and begin doing.",
        "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.",
        "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.",
        "When you reach the end of your rope, tie a knot in it and hang on.",
        "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
        "It is during our darkest moments that we must focus to see the light.",
        "Do not go where the path may lead, go instead where there is no path and leave a trail.",
        "Success usually comes to those who are too busy to be looking for it.",
        "If you really look closely, most overnight successes took a long time.",
        "The only place where success comes before work is in the dictionary.",
        "If you are not willing to risk the usual, you will have to settle for the ordinary." ,
        "Whether you think you can or you think you can't, you're right." ,
        "The question isn't who is going to let me; it's who is going to stop me.",
        "Everything you've ever wanted is on the other side of fear.",
        "Dream big and dare to fail.",
        "You may be disappointed if you fail, but you are doomed if you don't try.",
        "It does not matter how slowly you go as long as you do not stop.",
        "I didn't fail the test. I just found 100 ways to do it wrong."]
